// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aabrzhzpzabtyyuqzqbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhYnJ6aHpwemFidHl5dXF6cWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMjYzOTAsImV4cCI6MjA1MTkwMjM5MH0.AZhrVpKx2fxm2qw-WfGATN46zNxriQyDb9WgP-wIe7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);